version: "3.8"

services:
  wordpress-php-fpm:
    build: .
    image: mwaeckerlin/wordpress-php-fpm
    environment:
      WORDPRESS_DB_HOST:
      WORDPRESS_DB_NAME:
      WORDPRESS_DB_USER:
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_CHARSET:
      WORDPRESS_DB_COLLATE:
      WORDPRESS_TABLE_PREFIX:
      WORDPRESS_AUTH_KEY:
      WORDPRESS_SECURE_AUTH_KEY:
      WORDPRESS_LOGGED_IN_KEY:
      WORDPRESS_NONCE_KEY:
      WORDPRESS_AUTH_SALT:
      WORDPRESS_SECURE_AUTH_SALT:
      WORDPRESS_LOGGED_IN_SALT:
      WORDPRESS_NONCE_SALT:
      WORDPRESS_HOME:
      WORDPRESS_SITEURL:
      WORDPRESS_DEBUG:
    networks:
      default:
        aliases:
          - php-fpm
